### ISSUE TITLE
Error installing with pip Mac M1

### ISSUE THREAD

**Issue by victorbstan** [measuredweighed/BSP2OBJ#1]
I got this error when trying to install with pip

```
Collecting enum
  Using cached enum-0.4.7.tar.gz (20 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      /opt/homebrew/lib/python3.9/site-packages/setuptools/version.py:1: UserWarning: Module enum was already imported from /opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py, but /private/var/folders/jv/qyrqps1d4ydf0w7w4284bgb40000gn/T/pip-install-4z89xv00/enum_fb2d87c1959843c8b7cea6631be25ef1 is being added to sys.path
        import pkg_resources
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/jv/qyrqps1d4ydf0w7w4284bgb40000gn/T/pip-install-4z89xv00/enum_fb2d87c1959843c8b7cea6631be25ef1/setup.py", line 24, in <module>
          version = main_module.__version__
      AttributeError: module 'enum' has no attribute '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by nukadelic** [comment]
I have tried the following configurations but none worked :
```
Python 3.11, 3.12 : 
AttributeError: module 'enum' has no attribute 'global_enum'

Python 3.8 , 3.9 , 3.10 :
AttributeError: module 'enum' has no attribute 'IntFlag'

Python 3.5 : 
ImportError: cannot import name 'IntEnum'
```

To fix it , try installing it without enum34 then adding it manually : 
```
conda create -n source python=3.8 pip --yes && conda activate source
pip install git+https://github.com/nukadelic/BSP2OBJ
pip install enum34
```
which seemed to work for me
