### ISSUE TITLE
Unpack error

### ISSUE THREAD

**Issue by Lufims** [measuredweighed/BSP2OBJ#3]
Some maps just doesn't convert, something related to the unpacking.
```
BSP version 30
Traceback (most recent call last):
  File "C:\Users\LUÍS\AppData\Local\Programs\Python\Python310\lib\site-packages\bsp2obj-0.3-py3.10.egg\bsp2obj\command_line.py", line 59, in main
    bsp = BSP(data, paks, palettePath, game)
  File "C:\Users\LUÍS\AppData\Local\Programs\Python\Python310\lib\site-packages\bsp2obj-0.3-py3.10.egg\bsp2obj\bsp.py", line 79, in __init__
    self.textures = self.parseTextures(lumps[2])
  File "C:\Users\LUÍS\AppData\Local\Programs\Python\Python310\lib\site-packages\bsp2obj-0.3-py3.10.egg\bsp2obj\bsp.py", line 318, in parseTextures
    textures.append(TextureLoader.loadWAL(self.game, self.data, self.palette))
  File "C:\Users\LUÍS\AppData\Local\Programs\Python\Python310\lib\site-packages\bsp2obj-0.3-py3.10.egg\bsp2obj\image.py", line 93, in loadWAL
    index, = struct.unpack("B", data.read(1))
struct.error: unpack requires a buffer of 1 bytes
```
I tried to convert "boot_camp"

**Comment by measuredweighed** [comment]
Would you be able to provide the command line arguments you're using and also a link to download the `boot_camp` map?

**Comment by Lufims** [comment]
> Would you be able to provide the command line arguments you're using and also a link to download the `boot_camp` map?

here's the maps and gfx folders, in the maps folder have a script that I made to mass convert the maps, I think it will be more easy to see on what maps it doesn't work.

https://drive.google.com/file/d/1NbfWQ4Qr-00D1fe20GKyiPxsLGlmFFZV/view?usp=sharing

And the command line is this:
`bsp2obj -g hl1 -o boot_camp -m C:/Users/LUÍS/Desktop/valve/maps/boot_camp.bsp -c C:/Users/LUÍS/Desktop/valve/gfx/palette.lmp`

**Comment by forbenaj** [comment]
This is probably due to the map requiring an external WAD file. Any way to include these? Would be great for maps from mods

**Comment by Rohlo** [comment]
> This is probably due to the map requiring an external WAD file. Any way to include these? Would be great for maps from mods

Running into this error at the moment, did you manage to figure out a solution? At the moment I am looking at attempting to just check if there is a missing texture and not add any polygons with that texture assignment, but obviously that is not ideal. It seems like these textures might be used for decals/vfx?

**Comment by Rohlo** [comment]
> This is probably due to the map requiring an external WAD file. Any way to include these? Would be great for maps from mods

It's definitely external WADS, and despite the TODO comment in the code saying the author has yet to come across this, there are a LOT of maps that link to external wads, hell half of the first HL1 tram ride does.

I have modified my own version so it at least extracts the texture name and dimensions from the WAD so the UV's and exported materials references are right, It works, but it no longer extracts pixel data to creates PNG's, instead I extracted the WAD texture data with a separate app.

I might see if I can get it functioning similar to the original plugin and make a branch.

**Comment by forbenaj** [comment]
> I might see if I can get it functioning similar to the original plugin and make a branch.

That would be wonderful.
Honestly I'm just trying to use this one because I'm stuck with ubuntu, but I tried in the past a Windows pipeline that worked well. Will try soon.

**Comment by measuredweighed** [comment]
If anyone can point me to a WAD with an external dependency I'd be happy to take a look at this.
